name: Success - Set job enviroment dynamically using object format
on:
  workflow_dispatch:
jobs:
  set_environment:
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: echo "my_env=production" >> $GITHUB_OUTPUT

  use_outputs_environemnt:
    needs: set_environment
    environment:
      name: ${{ needs.set_environment.outputs.my_env }}
      url: test
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: echo "Hello From Production Envrionment."
