name: Success - Set job enviroment dynamically using object format
on:
  workflow_dispatch:
    inputs:
      environment:
         type: environment
         description: Select the environment    
jobs:
  use_outputs_environemnt:
    environment:
      name:  ${{ inputs.environment }}
      url: http://test.com
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: echo "Hello From  ${{ inputs.environment }} Envrionment."
