name: GitHub Actions Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - uses: azure/setup-helm@v1
        id: install
      - name: Install redis
        run: |
          helm upgrade --install --wait --timeout 600s redis redis-cluster --repo https://charts.bitnami.com/bitnami --namespace redis --create-namespace
      - name: Install ingress
        run: |
          helm upgrade --install --wait ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
      - run: |
          kubectl get all -A
